spring:
  application:
    name: book_application
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bookrental
    username: postgres
    password: 081725
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml.yaml
    contexts: local
    enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8080

#jpa:
#  hibernate:
#    ddl-auto: validate
#  show-sql: true
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect

#springdoc:
#  group-configs:
#    - group: library
#      paths-to-match: /api/library/**
xc-config:
  database:
    sequence:
      book: book_seq
      rent-history: rent_history_seq
      point: point_seq